export const estudiantesData = [
  { name: "Preescolar", value: 120, color: "#8884d8" },
  { name: "Primaria", value: 350, color: "#82ca9d" },
  { name: "Secundaria", value: 280, color: "#ffc658" },
]

export const empleadosData = [
  { name: "Profesores", cantidad: 45 },
  { name: "Administrativo", cantidad: 12 },
  { name: "Generales", cantidad: 8 },
]

export const usuariosList = [
  { id: 1, nombre: "María García", correo: "maria.garcia@colegio.edu.co", rol: "Directora", estado: "Activo" },
  { id: 2, nombre: "Carlos López", correo: "carlos.lopez@colegio.edu.co", rol: "Profesor", estado: "Activo" },
  { id: 3, nombre: "Ana Martínez", correo: "ana.martinez@colegio.edu.co", rol: "Coordinadora", estado: "Activo" },
  { id: 4, nombre: "Luis Rodríguez", correo: "luis.rodriguez@colegio.edu.co", rol: "Profesor", estado: "Inactivo" },
  { id: 5, nombre: "Carmen Díaz", correo: "carmen.diaz@colegio.edu.co", rol: "Secretaria", estado: "Activo" },
]

export const rolesList = [
  {
    id: 1,
    nombre: "Super Administrador",
    descripcion: "Acceso completo al sistema",
    permisos: ["crear", "leer", "actualizar", "eliminar", "gestionar_usuarios", "gestionar_roles"],
    usuariosAsignados: 2,
  },
  {
    id: 2,
    nombre: "Directora",
    descripcion: "Gestión académica y administrativa",
    permisos: ["crear", "leer", "actualizar", "gestionar_usuarios"],
    usuariosAsignados: 1,
  },
  {
    id: 3,
    nombre: "Profesor",
    descripcion: "Gestión de clases y estudiantes",
    permisos: ["leer", "actualizar"],
    usuariosAsignados: 25,
  },
]

export const aulasList = [
  {
    id: 1,
    nombre: "Aula 101",
    capacidad: 30,
    ubicacion: "Primer piso, Bloque A",
    tipo: "Aula estándar",
    equipamiento: "Proyector, Pizarra digital, Aire acondicionado",
    estado: "disponible",
  },
  {
    id: 2,
    nombre: "Laboratorio de Ciencias",
    capacidad: 25,
    ubicacion: "Segundo piso, Bloque B",
    tipo: "Laboratorio",
    equipamiento: "Microscopios, Material de laboratorio, Campana extractora",
    estado: "ocupado",
  },
]

export const eventosList = [
  {
    id: 1,
    titulo: "Reunión de Padres",
    descripcion: "Reunión trimestral con padres de familia para revisar el progreso académico",
    fechaInicio: "2024-02-15",
    fechaFin: "2024-02-15",
    horaInicio: "14:00",
    horaFin: "16:00",
    ubicacion: "Auditorio Principal",
    categoria: "Académico",
    imagen: "/reunion-padres.jpg",
    estado: "programado",
  },
  {
    id: 2,
    titulo: "Festival de Ciencias",
    descripcion: "Exposición de proyectos científicos realizados por estudiantes de todos los grados",
    fechaInicio: "2024-02-20",
    fechaFin: "2024-02-22",
    horaInicio: "08:00",
    horaFin: "17:00",
    ubicacion: "Patio Central",
    categoria: "Cultural",
    imagen: "/festival-ciencias.jpg",
    estado: "programado",
  },
  {
    id: 3,
    titulo: "Día del Deporte",
    descripcion: "Competencias deportivas inter-cursos con participación de toda la comunidad educativa",
    fechaInicio: "2024-02-25",
    fechaFin: "2024-02-25",
    horaInicio: "07:00",
    horaFin: "15:00",
    ubicacion: "Cancha Deportiva",
    categoria: "Deportivo",
    imagen: "/dia-deporte.jpg",
    estado: "programado",
  },
  {
    id: 4,
    titulo: "Graduación Bachilleres",
    descripcion: "Ceremonia de graduación para estudiantes de grado 11",
    fechaInicio: "2024-03-15",
    fechaFin: "2024-03-15",
    horaInicio: "18:00",
    horaFin: "21:00",
    ubicacion: "Auditorio Principal",
    categoria: "Ceremonial",
    imagen: "/graduacion.jpg",
    estado: "programado",
  },
]

export const categoriaEventos = ["Académico", "Cultural", "Deportivo", "Ceremonial", "Administrativo"]

export const COLORS = ["#8884d8", "#82ca9d", "#ffc658"]

export const ticketsList = [
  {
    id: 1,
    titulo: "Problema con acceso a plataforma",
    descripcion: "No puedo ingresar a la plataforma educativa con mis credenciales",
    usuario: "Ana Pérez",
    correo: "ana.perez@estudiante.edu.co",
    tipo: "Técnico",
    prioridad: "Alta",
    estado: "Abierto",
    fechaCreacion: "2024-02-10",
    fechaActualizacion: "2024-02-10",
    respuestas: [
      {
        id: 1,
        autor: "Soporte Técnico",
        mensaje: "Hemos recibido tu consulta. Estamos revisando el problema de acceso.",
        fecha: "2024-02-10 14:30",
      },
    ],
  },
  {
    id: 2,
    titulo: "Consulta sobre calificaciones",
    descripcion: "Quisiera revisar las calificaciones de mi hijo en matemáticas del segundo período",
    usuario: "Carlos Martínez",
    correo: "carlos.martinez@padre.edu.co",
    tipo: "Académico",
    prioridad: "Media",
    estado: "En proceso",
    fechaCreacion: "2024-02-08",
    fechaActualizacion: "2024-02-09",
    respuestas: [
      {
        id: 1,
        autor: "Coordinación Académica",
        mensaje: "Hola Carlos, hemos revisado las calificaciones. Te enviaremos el reporte detallado.",
        fecha: "2024-02-09 10:15",
      },
      {
        id: 2,
        autor: "Carlos Martínez",
        mensaje: "Perfecto, quedo atento al reporte. Gracias por la atención.",
        fecha: "2024-02-09 11:00",
      },
    ],
  },
  {
    id: 3,
    titulo: "Solicitud de certificado de estudios",
    descripcion: "Necesito un certificado de estudios para trámites universitarios",
    usuario: "María González",
    correo: "maria.gonzalez@estudiante.edu.co",
    tipo: "Administrativo",
    prioridad: "Media",
    estado: "Resuelto",
    fechaCreacion: "2024-02-05",
    fechaActualizacion: "2024-02-07",
    respuestas: [
      {
        id: 1,
        autor: "Secretaría Académica",
        mensaje: "Tu certificado está listo. Puedes recogerlo en secretaría de 8:00 AM a 4:00 PM.",
        fecha: "2024-02-07 09:00",
      },
    ],
  },
  {
    id: 4,
    titulo: "Queja sobre servicio de cafetería",
    descripcion: "La calidad de los alimentos en la cafetería ha disminuido considerablemente",
    usuario: "Luis Rodríguez",
    correo: "luis.rodriguez@estudiante.edu.co",
    tipo: "Servicios",
    prioridad: "Baja",
    estado: "Abierto",
    fechaCreacion: "2024-02-12",
    fechaActualizacion: "2024-02-12",
    respuestas: [],
  },
  {
    id: 5,
    titulo: "Problema con transporte escolar",
    descripcion: "El bus de la ruta 3 ha llegado tarde los últimos 5 días",
    usuario: "Carmen Díaz",
    correo: "carmen.diaz@padre.edu.co",
    tipo: "Transporte",
    prioridad: "Alta",
    estado: "En proceso",
    fechaCreacion: "2024-02-11",
    fechaActualizacion: "2024-02-12",
    respuestas: [
      {
        id: 1,
        autor: "Coordinación de Transporte",
        mensaje: "Hemos contactado al conductor. Se implementarán medidas para mejorar la puntualidad.",
        fecha: "2024-02-12 08:30",
      },
    ],
  },
]

export const tiposTicket = ["Técnico", "Académico", "Administrativo", "Servicios", "Transporte"]
export const estadosTicket = ["Abierto", "En proceso", "Resuelto", "Cerrado"]
export const prioridadesTicket = ["Baja", "Media", "Alta", "Urgente"]

export const conversacionesList = [
  {
    id: 1,
    usuario: {
      nombre: "María García",
      correo: "maria.garcia@colegio.edu.co",
      avatar: "/portrait-thoughtful-woman.png",
      estado: "en línea",
      ultimaConexion: "Ahora",
    },
    ultimoMensaje: "Perfecto, nos vemos mañana en la reunión",
    fechaUltimoMensaje: "2024-02-15 14:30",
    mensajesNoLeidos: 0,
    mensajes: [
      {
        id: 1,
        autor: "María García",
        mensaje: "Hola, ¿podemos revisar el informe académico?",
        fecha: "2024-02-15 14:15",
        leido: true,
      },
      {
        id: 2,
        autor: "Admin",
        mensaje: "Por supuesto, ¿te parece bien mañana a las 10 AM?",
        fecha: "2024-02-15 14:20",
        leido: true,
      },
      {
        id: 3,
        autor: "María García",
        mensaje: "Perfecto, nos vemos mañana en la reunión",
        fecha: "2024-02-15 14:30",
        leido: true,
      },
    ],
  },
  {
    id: 2,
    usuario: {
      nombre: "Carlos López",
      correo: "carlos.lopez@colegio.edu.co",
      avatar: "/portrait-carlos.png",
      estado: "en línea",
      ultimaConexion: "Hace 5 min",
    },
    ultimoMensaje: "Los estudiantes están muy motivados con el proyecto",
    fechaUltimoMensaje: "2024-02-15 13:45",
    mensajesNoLeidos: 2,
    mensajes: [
      {
        id: 1,
        autor: "Carlos López",
        mensaje: "El proyecto de ciencias va muy bien",
        fecha: "2024-02-15 13:30",
        leido: true,
      },
      {
        id: 2,
        autor: "Admin",
        mensaje: "Excelente, ¿necesitas algún material adicional?",
        fecha: "2024-02-15 13:35",
        leido: true,
      },
      {
        id: 3,
        autor: "Carlos López",
        mensaje: "Los estudiantes están muy motivados con el proyecto",
        fecha: "2024-02-15 13:45",
        leido: false,
      },
    ],
  },
  {
    id: 3,
    usuario: {
      nombre: "Ana Martínez",
      correo: "ana.martinez@colegio.edu.co",
      avatar: "/ana-abstract-geometric.png",
      estado: "ausente",
      ultimaConexion: "Hace 2 horas",
    },
    ultimoMensaje: "Enviaré el cronograma esta tarde",
    fechaUltimoMensaje: "2024-02-15 11:20",
    mensajesNoLeidos: 0,
    mensajes: [
      {
        id: 1,
        autor: "Admin",
        mensaje: "¿Tienes listo el cronograma de actividades?",
        fecha: "2024-02-15 11:00",
        leido: true,
      },
      {
        id: 2,
        autor: "Ana Martínez",
        mensaje: "Enviaré el cronograma esta tarde",
        fecha: "2024-02-15 11:20",
        leido: true,
      },
    ],
  },
  {
    id: 4,
    usuario: {
      nombre: "Luis Rodríguez",
      correo: "luis.rodriguez@colegio.edu.co",
      avatar: "/luis.jpg",
      estado: "ocupado",
      ultimaConexion: "Hace 1 hora",
    },
    ultimoMensaje: "Gracias por la información",
    fechaUltimoMensaje: "2024-02-15 12:15",
    mensajesNoLeidos: 1,
    mensajes: [
      {
        id: 1,
        autor: "Admin",
        mensaje: "Recuerda la capacitación de mañana",
        fecha: "2024-02-15 12:00",
        leido: true,
      },
      {
        id: 2,
        autor: "Luis Rodríguez",
        mensaje: "Gracias por la información",
        fecha: "2024-02-15 12:15",
        leido: false,
      },
    ],
  },
]

export const usuariosDisponibles = [
  {
    id: 5,
    nombre: "Carmen Díaz",
    correo: "carmen.diaz@colegio.edu.co",
    avatar: "/woman-in-red-dress.png",
    estado: "en línea",
    rol: "Secretaria",
  },
  {
    id: 6,
    nombre: "Diego Morales",
    correo: "diego.morales@colegio.edu.co",
    avatar: "/diego.jpg",
    estado: "ausente",
    rol: "Profesor",
  },
]

export const estadosUsuario = ["en línea", "ausente", "ocupado", "no disponible"]

export const rutasList = [
  {
    id: 1,
    nombre: "Ruta Norte",
    conductor: {
      nombre: "Roberto Sánchez",
      telefono: "300-123-4567",
      licencia: "C2-12345678",
    },
    vehiculo: {
      placa: "ABC-123",
      modelo: "Mercedes Benz Sprinter 2020",
      capacidad: 25,
      estado: "Activo",
    },
    horarios: {
      salida: "06:30",
      llegada: "07:30",
      salidaTarde: "14:00",
      llegadaTarde: "15:00",
    },
    paradas: [
      "Centro Comercial Unicentro",
      "Barrio Los Rosales",
      "Conjunto Villa del Río",
      "Parque Principal",
      "Colegio",
    ],
    estudiantes: [
      { id: 1, nombre: "Sofía Ramírez", grado: "5°A", parada: "Centro Comercial Unicentro" },
      { id: 2, nombre: "Andrés Moreno", grado: "8°B", parada: "Barrio Los Rosales" },
      { id: 3, nombre: "Valentina Cruz", grado: "3°C", parada: "Conjunto Villa del Río" },
      { id: 4, nombre: "Santiago López", grado: "6°A", parada: "Parque Principal" },
      { id: 5, nombre: "Isabella García", grado: "4°B", parada: "Centro Comercial Unicentro" },
    ],
    estado: "Activa",
  },
  {
    id: 2,
    nombre: "Ruta Sur",
    conductor: {
      nombre: "Miguel Ángel Torres",
      telefono: "301-987-6543",
      licencia: "C2-87654321",
    },
    vehiculo: {
      placa: "DEF-456",
      modelo: "Chevrolet NPR 2019",
      capacidad: 30,
      estado: "Activo",
    },
    horarios: {
      salida: "06:45",
      llegada: "07:45",
      salidaTarde: "14:15",
      llegadaTarde: "15:15",
    },
    paradas: ["Terminal de Transporte", "Barrio San José", "Urbanización El Prado", "Plaza de Mercado", "Colegio"],
    estudiantes: [
      { id: 6, nombre: "Camila Herrera", grado: "7°A", parada: "Terminal de Transporte" },
      { id: 7, nombre: "Mateo Jiménez", grado: "9°B", parada: "Barrio San José" },
      { id: 8, nombre: "Lucía Vargas", grado: "2°A", parada: "Urbanización El Prado" },
      { id: 9, nombre: "Sebastián Ruiz", grado: "5°C", parada: "Plaza de Mercado" },
      { id: 10, nombre: "Mariana Castillo", grado: "1°B", parada: "Terminal de Transporte" },
      { id: 11, nombre: "Nicolás Peña", grado: "10°A", parada: "Barrio San José" },
    ],
    estado: "Activa",
  },
  {
    id: 3,
    nombre: "Ruta Este",
    conductor: {
      nombre: "Carmen Elena Vásquez",
      telefono: "302-456-7890",
      licencia: "C2-45678912",
    },
    vehiculo: {
      placa: "GHI-789",
      modelo: "Iveco Daily 2021",
      capacidad: 20,
      estado: "Mantenimiento",
    },
    horarios: {
      salida: "07:00",
      llegada: "08:00",
      salidaTarde: "14:30",
      llegadaTarde: "15:30",
    },
    paradas: ["Estadio Municipal", "Barrio La Esperanza", "Centro Médico", "Universidad Local", "Colegio"],
    estudiantes: [
      { id: 12, nombre: "Alejandra Mendoza", grado: "11°A", parada: "Estadio Municipal" },
      { id: 13, nombre: "Daniel Ortiz", grado: "4°A", parada: "Barrio La Esperanza" },
      { id: 14, nombre: "Gabriela Silva", grado: "6°B", parada: "Centro Médico" },
      { id: 15, nombre: "Emilio Rojas", grado: "8°A", parada: "Universidad Local" },
    ],
    estado: "Mantenimiento",
  },
  {
    id: 4,
    nombre: "Ruta Oeste",
    conductor: {
      nombre: "Fernando Aguilar",
      telefono: "303-789-0123",
      licencia: "C2-78901234",
    },
    vehiculo: {
      placa: "JKL-012",
      modelo: "Ford Transit 2020",
      capacidad: 18,
      estado: "Activo",
    },
    horarios: {
      salida: "06:15",
      llegada: "07:15",
      salidaTarde: "13:45",
      llegadaTarde: "14:45",
    },
    paradas: ["Aeropuerto", "Zona Industrial", "Barrio Obrero", "Centro Histórico", "Colegio"],
    estudiantes: [
      { id: 16, nombre: "Valeria Gómez", grado: "9°A", parada: "Aeropuerto" },
      { id: 17, nombre: "Joaquín Morales", grado: "3°B", parada: "Zona Industrial" },
      { id: 18, nombre: "Antonella Díaz", grado: "7°C", parada: "Barrio Obrero" },
      { id: 19, nombre: "Maximiliano Rey", grado: "5°A", parada: "Centro Histórico" },
      { id: 20, nombre: "Renata Campos", grado: "2°C", parada: "Aeropuerto" },
    ],
    estado: "Activa",
  },
]

export const estadosRuta = ["Activa", "Inactiva", "Mantenimiento"]
export const estadosVehiculo = ["Activo", "Mantenimiento", "Fuera de servicio"]

export const registrosPsicologia = [
  {
    id: 1,
    estudiante: {
      nombre: "Ana Sofía Ramírez",
      grado: "8°A",
      edad: 14,
      avatar: "/portrait-thoughtful-woman.png",
    },
    motivo: "Ansiedad académica",
    descripcion:
      "La estudiante presenta síntomas de ansiedad relacionados con el rendimiento académico, especialmente en matemáticas.",
    fechaIngreso: "2024-01-15",
    ultimaConsulta: "2024-02-10",
    numeroSesiones: 6,
    estado: "En tratamiento",
    psicologo: "Dra. Patricia Morales",
    observaciones: "Progreso positivo. Se recomienda continuar con técnicas de relajación y apoyo familiar.",
    proximaCita: "2024-02-17",
  },
  {
    id: 2,
    estudiante: {
      nombre: "Carlos Andrés López",
      grado: "5°B",
      edad: 11,
      avatar: "/portrait-carlos.png",
    },
    motivo: "Problemas de conducta",
    descripcion: "Comportamiento disruptivo en clase, dificultades para seguir normas y relacionarse con compañeros.",
    fechaIngreso: "2024-01-20",
    ultimaConsulta: "2024-02-12",
    numeroSesiones: 8,
    estado: "En tratamiento",
    psicologo: "Psic. Miguel Ángel Torres",
    observaciones: "Se ha observado mejora en el control de impulsos. Trabajo conjunto con padres y docentes.",
    proximaCita: "2024-02-19",
  },
  {
    id: 3,
    estudiante: {
      nombre: "María Valentina Cruz",
      grado: "11°A",
      edad: 17,
      avatar: "/ana-abstract-geometric.png",
    },
    motivo: "Orientación vocacional",
    descripcion: "Solicita apoyo para la elección de carrera universitaria y manejo de estrés pre-universitario.",
    fechaIngreso: "2024-02-01",
    ultimaConsulta: "2024-02-14",
    numeroSesiones: 4,
    estado: "En tratamiento",
    psicologo: "Dra. Patricia Morales",
    observaciones: "Aplicación de test vocacionales. Estudiante con claridad en sus intereses académicos.",
    proximaCita: "2024-02-21",
  },
  {
    id: 4,
    estudiante: {
      nombre: "Santiago Moreno",
      grado: "3°C",
      edad: 9,
      avatar: "/luis.jpg",
    },
    motivo: "Dificultades de aprendizaje",
    descripcion: "Presenta dificultades en lectoescritura y concentración. Posible trastorno de atención.",
    fechaIngreso: "2023-11-10",
    ultimaConsulta: "2024-02-08",
    numeroSesiones: 12,
    estado: "Seguimiento",
    psicologo: "Psic. Miguel Ángel Torres",
    observaciones: "Remitido a neuropsicología. Implementación de estrategias pedagógicas diferenciadas.",
    proximaCita: "2024-02-22",
  },
  {
    id: 5,
    estudiante: {
      nombre: "Isabella García",
      grado: "6°A",
      edad: 12,
      avatar: "/woman-in-red-dress.png",
    },
    motivo: "Duelo familiar",
    descripcion: "Proceso de duelo por pérdida de familiar cercano. Afectación en rendimiento académico y social.",
    fechaIngreso: "2023-12-05",
    ultimaConsulta: "2024-02-13",
    numeroSesiones: 10,
    estado: "Alta",
    psicologo: "Dra. Patricia Morales",
    observaciones: "Proceso de duelo elaborado satisfactoriamente. Reintegración social exitosa.",
    proximaCita: null,
  },
  {
    id: 6,
    estudiante: {
      nombre: "Mateo Jiménez",
      grado: "9°B",
      edad: 15,
      avatar: "/diego.jpg",
    },
    motivo: "Bullying",
    descripcion: "Víctima de acoso escolar. Presenta síntomas de depresión y aislamiento social.",
    fechaIngreso: "2024-01-08",
    ultimaConsulta: "2024-02-11",
    numeroSesiones: 7,
    estado: "En tratamiento",
    psicologo: "Psic. Miguel Ángel Torres",
    observaciones: "Intervención grupal implementada. Mejora en autoestima y habilidades sociales.",
    proximaCita: "2024-02-18",
  },
]

export const motivosPsicologia = [
  { motivo: "Ansiedad académica", cantidad: 15, porcentaje: 25 },
  { motivo: "Problemas de conducta", cantidad: 12, porcentaje: 20 },
  { motivo: "Dificultades de aprendizaje", cantidad: 10, porcentaje: 17 },
  { motivo: "Orientación vocacional", cantidad: 8, porcentaje: 13 },
  { motivo: "Bullying", cantidad: 6, porcentaje: 10 },
  { motivo: "Duelo familiar", cantidad: 5, porcentaje: 8 },
  { motivo: "Problemas familiares", cantidad: 4, porcentaje: 7 },
]

export const estadosPsicologia = ["En tratamiento", "Seguimiento", "Alta", "Remitido"]
export const psicologos = ["Dra. Patricia Morales", "Psic. Miguel Ángel Torres"]

export const profesoresList = [
  {
    id: 1,
    nombre: "María García",
    especialidad: "Matemáticas",
    correo: "maria.garcia@colegio.edu.co",
    telefono: "300-123-4567",
  },
  {
    id: 2,
    nombre: "Carlos López",
    especialidad: "Ciencias Naturales",
    correo: "carlos.lopez@colegio.edu.co",
    telefono: "301-234-5678",
  },
  {
    id: 3,
    nombre: "Ana Martínez",
    especialidad: "Español",
    correo: "ana.martinez@colegio.edu.co",
    telefono: "302-345-6789",
  },
  {
    id: 4,
    nombre: "Luis Rodríguez",
    especialidad: "Educación Física",
    correo: "luis.rodriguez@colegio.edu.co",
    telefono: "303-456-7890",
  },
  {
    id: 5,
    nombre: "Carmen Díaz",
    especialidad: "Inglés",
    correo: "carmen.diaz@colegio.edu.co",
    telefono: "304-567-8901",
  },
]

export const cursosList = [
  { id: 1, grado: "1°A", numeroEstudiantes: 25 },
  { id: 2, grado: "1°B", numeroEstudiantes: 24 },
  { id: 3, grado: "2°A", numeroEstudiantes: 26 },
  { id: 4, grado: "2°B", numeroEstudiantes: 25 },
  { id: 5, grado: "3°A", numeroEstudiantes: 28 },
  { id: 6, grado: "3°B", numeroEstudiantes: 27 },
  { id: 7, grado: "4°A", numeroEstudiantes: 29 },
  { id: 8, grado: "4°B", numeroEstudiantes: 28 },
  { id: 9, grado: "5°A", numeroEstudiantes: 30 },
  { id: 10, grado: "5°B", numeroEstudiantes: 29 },
  { id: 11, grado: "6°A", numeroEstudiantes: 32 },
  { id: 12, grado: "6°B", numeroEstudiantes: 31 },
  { id: 13, grado: "7°A", numeroEstudiantes: 33 },
  { id: 14, grado: "7°B", numeroEstudiantes: 32 },
  { id: 15, grado: "8°A", numeroEstudiantes: 34 },
  { id: 16, grado: "8°B", numeroEstudiantes: 33 },
  { id: 17, grado: "9°A", numeroEstudiantes: 35 },
  { id: 18, grado: "9°B", numeroEstudiantes: 34 },
  { id: 19, grado: "10°A", numeroEstudiantes: 36 },
  { id: 20, grado: "10°B", numeroEstudiantes: 35 },
  { id: 21, grado: "11°A", numeroEstudiantes: 37 },
  { id: 22, grado: "11°B", numeroEstudiantes: 36 },
]

export const horariosList = [
  {
    id: 1,
    profesor: "María García",
    materia: "Matemáticas",
    curso: "8°A",
    aula: "Aula 201",
    dia: "Lunes",
    horaInicio: "07:00",
    horaFin: "08:00",
  },
  {
    id: 2,
    profesor: "María García",
    materia: "Matemáticas",
    curso: "8°B",
    aula: "Aula 201",
    dia: "Lunes",
    horaInicio: "08:00",
    horaFin: "09:00",
  },
  {
    id: 3,
    profesor: "Carlos López",
    materia: "Ciencias Naturales",
    curso: "7°A",
    aula: "Laboratorio",
    dia: "Lunes",
    horaInicio: "09:00",
    horaFin: "10:00",
  },
  {
    id: 4,
    profesor: "Ana Martínez",
    materia: "Español",
    curso: "6°A",
    aula: "Aula 102",
    dia: "Lunes",
    horaInicio: "10:00",
    horaFin: "11:00",
  },
  {
    id: 5,
    profesor: "Luis Rodríguez",
    materia: "Educación Física",
    curso: "5°A",
    aula: "Cancha",
    dia: "Lunes",
    horaInicio: "11:00",
    horaFin: "12:00",
  },
  {
    id: 6,
    profesor: "Carmen Díaz",
    materia: "Inglés",
    curso: "9°A",
    aula: "Aula 301",
    dia: "Martes",
    horaInicio: "07:00",
    horaFin: "08:00",
  },
  {
    id: 7,
    profesor: "María García",
    materia: "Matemáticas",
    curso: "9°B",
    aula: "Aula 201",
    dia: "Martes",
    horaInicio: "08:00",
    horaFin: "09:00",
  },
  {
    id: 8,
    profesor: "Carlos López",
    materia: "Ciencias Naturales",
    curso: "8°A",
    aula: "Laboratorio",
    dia: "Martes",
    horaInicio: "09:00",
    horaFin: "10:00",
  },
  {
    id: 9,
    profesor: "Ana Martínez",
    materia: "Español",
    curso: "7°B",
    aula: "Aula 102",
    dia: "Martes",
    horaInicio: "10:00",
    horaFin: "11:00",
  },
  {
    id: 10,
    profesor: "Luis Rodríguez",
    materia: "Educación Física",
    curso: "6°B",
    aula: "Cancha",
    dia: "Martes",
    horaInicio: "11:00",
    horaFin: "12:00",
  },
  {
    id: 11,
    profesor: "Carmen Díaz",
    materia: "Inglés",
    curso: "10°A",
    aula: "Aula 301",
    dia: "Miércoles",
    horaInicio: "07:00",
    horaFin: "08:00",
  },
  {
    id: 12,
    profesor: "María García",
    materia: "Matemáticas",
    curso: "11°A",
    aula: "Aula 201",
    dia: "Miércoles",
    horaInicio: "08:00",
    horaFin: "09:00",
  },
  {
    id: 13,
    profesor: "Carlos López",
    materia: "Ciencias Naturales",
    curso: "9°A",
    aula: "Laboratorio",
    dia: "Miércoles",
    horaInicio: "09:00",
    horaFin: "10:00",
  },
  {
    id: 14,
    profesor: "Ana Martínez",
    materia: "Español",
    curso: "8°B",
    aula: "Aula 102",
    dia: "Miércoles",
    horaInicio: "10:00",
    horaFin: "11:00",
  },
  {
    id: 15,
    profesor: "Luis Rodríguez",
    materia: "Educación Física",
    curso: "7°A",
    aula: "Cancha",
    dia: "Miércoles",
    horaInicio: "11:00",
    horaFin: "12:00",
  },
  {
    id: 16,
    profesor: "Carmen Díaz",
    materia: "Inglés",
    curso: "11°B",
    aula: "Aula 301",
    dia: "Jueves",
    horaInicio: "07:00",
    horaFin: "08:00",
  },
  {
    id: 17,
    profesor: "María García",
    materia: "Matemáticas",
    curso: "10°B",
    aula: "Aula 201",
    dia: "Jueves",
    horaInicio: "08:00",
    horaFin: "09:00",
  },
  {
    id: 18,
    profesor: "Carlos López",
    materia: "Ciencias Naturales",
    curso: "6°A",
    aula: "Laboratorio",
    dia: "Jueves",
    horaInicio: "09:00",
    horaFin: "10:00",
  },
  {
    id: 19,
    profesor: "Ana Martínez",
    materia: "Español",
    curso: "5°B",
    aula: "Aula 102",
    dia: "Jueves",
    horaInicio: "10:00",
    horaFin: "11:00",
  },
  {
    id: 20,
    profesor: "Luis Rodríguez",
    materia: "Educación Física",
    curso: "4°A",
    aula: "Cancha",
    dia: "Jueves",
    horaInicio: "11:00",
    horaFin: "12:00",
  },
  {
    id: 21,
    profesor: "Carmen Díaz",
    materia: "Inglés",
    curso: "3°A",
    aula: "Aula 301",
    dia: "Viernes",
    horaInicio: "07:00",
    horaFin: "08:00",
  },
  {
    id: 22,
    profesor: "María García",
    materia: "Matemáticas",
    curso: "2°A",
    aula: "Aula 201",
    dia: "Viernes",
    horaInicio: "08:00",
    horaFin: "09:00",
  },
  {
    id: 23,
    profesor: "Carlos López",
    materia: "Ciencias Naturales",
    curso: "1°A",
    aula: "Laboratorio",
    dia: "Viernes",
    horaInicio: "09:00",
    horaFin: "10:00",
  },
  {
    id: 24,
    profesor: "Ana Martínez",
    materia: "Español",
    curso: "4°B",
    aula: "Aula 102",
    dia: "Viernes",
    horaInicio: "10:00",
    horaFin: "11:00",
  },
  {
    id: 25,
    profesor: "Luis Rodríguez",
    materia: "Educación Física",
    curso: "3°B",
    aula: "Cancha",
    dia: "Viernes",
    horaInicio: "11:00",
    horaFin: "12:00",
  },
]

export const diasSemana = ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes"]
export const horasClase = [
  "07:00 - 08:00",
  "08:00 - 09:00",
  "09:00 - 10:00",
  "10:00 - 11:00",
  "11:00 - 12:00",
  "13:00 - 14:00",
  "14:00 - 15:00",
  "15:00 - 16:00",
]
